NotesDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.functional import curry
from django.views.defaults import *
from rest_framework_jwt.views import obtain_jwt_token

handler500 = curry(server_error, template_name='500.html')
handler404 = curry(page_not_found, template_name="404.html")
handler403 = curry(permission_denied, template_name='403.html')


urlpatterns = [
    url(r'^', include('notes.urls', namespace='notes')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/users/', include('users.api.urls', namespace='users_api')),
    url(r'^api/notes/', include('notes.api.urls', namespace='notes_api')),
    url(r'^api/token/auth/', obtain_jwt_token),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/', include('allauth.urls')),

]

notes/api/urls.py
from django.conf.urls import url

from notes.api.views import NoteListAPIView, NoteDetailAPIView, NoteEditAPIView, NoteDeleteAPIView, NoteComposeAPIView

urlpatterns = [
    # ex: /notes or /notes?label=journal
    url(r'^$', NoteListAPIView.as_view(), name='list'),
    # ex: /notes/2
    url(r'^(?P<pk>[0-9]+)/$', NoteDetailAPIView.as_view(), name='detail'),
    # # ex: /notes/2/edit
    url(r'^(?P<pk>[0-9]+)/edit/$', NoteEditAPIView.as_view(), name='edit'),
    # # ex: /notes/2/edit
    url(r'^(?P<pk>[0-9]+)/delete/$', NoteDeleteAPIView.as_view(), name='delete'),
    # # ex: /notes/compose
    url(r'^compose/$', NoteComposeAPIView.as_view(), name='compose'),
]

notes/urls.py
from django.conf.urls import url

from . import views

app_name = 'notes'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),

    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteView.as_view(), name='delete'),

    url(r'^(?P<pk>[0-9]+)/unarchive/$', views.UnarchiveView.as_view(), name='unarchive'),

    url(r'^compose/$', views.ComposeView.as_view(), name='compose'),

    url(r'^newLabel/$', views.ComposeLabelView.as_view(), name='createLabel'),

    url(r'^(?P<pk>[0-9]+)/editLabel/$', views.EditLabelView.as_view(), name='editLabel'),

    url(r'^(?P<pk>[0-9]+)/deleteLabel/$', views.DeleteLabelView.as_view(), name='deleteLabel'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),

    # ex: /users/signup
    url(r'^signup/', views.SignupView.as_view(), name='signup'),
    # ex: /users/login
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    # ex: /users/logout
    url(r'^logout/', auth_views.logout, name='logout'),
    # ex: /users/profile
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
]

notes/models.py
from colorful.fields import RGBColorField
from django.contrib.auth.models import User
from django.db import models


class Note(models.Model):
    note_title = models.CharField(max_length=200)
    note_text = models.TextField(max_length=10000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    labels = models.ManyToManyField('Label', related_name='notes')
    public = models.BooleanField(default=0)
    archived = models.BooleanField(default=0)

    # pinned = models.BooleanField(default=0)

    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.timestamp <= now

    # def get_absolute_url(self):
    #     return reverse("notes:detail", kwargs={"slug": self.slug})
    #     # return reverse('notes:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.note_title

    class Meta:
        ordering = ["-timestamp", "-updated"]


# def create_slug(text, new_slug=None):
#     slug = slugify(text)
#     if new_slug is not None:
#         slug = new_slug
#     qs = Note.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug(text, new_slug=new_slug)
#     return slug
#
#
# #
# # def get_image_filename(filename):
# #     slug = create_slug(filename)
# #     return "post_images/%s" % slug
#
#
# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance.note_title)
#
#
# pre_save.connect(pre_save_post_receiver, sender=Note)


class Label(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200, default="")
    background_color = RGBColorField(default="#ffffff")
    text_color = RGBColorField(default="#000000")

    def __str__(self):
        return self.text

notes/forms.py
from django.forms import ModelForm

from .models import Note, Label


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ['note_title',
                  'note_text',
                  'labels',
                  'public',
                  'archived',
                  # 'pinned'
                  ]


class NoteArchiveForm(ModelForm):
    class Meta:
        model = Note
        fields = ['archived']


class LabelForm(ModelForm):
    class Meta:
        model = Label
        exclude = ('author',)

notes/api/views.py
from django.db.models import Q
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import ListAPIView, DestroyAPIView, RetrieveAPIView, CreateAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly

from notes.models import Note
from .permissions import IsOwnerOrReadOnly
from .serializers import NoteDetailSerializer, NoteListSerializer, NoteComposeUpdateSerializer


class NoteComposeAPIView(CreateAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteComposeUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        if not self.request.user.is_anonymous:
            serializer.save(author=self.request.user)
        else:
            pass


class NoteListAPIView(ListAPIView):
    serializer_class = NoteListSerializer
    filter_backends = [SearchFilter, OrderingFilter]

    def get_queryset(self):
        queryset = Note.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset = queryset.filter(
                Q(note_text__icontains=query) |
                Q(note_title__icontains=query) |
                Q(author__username__icontains=query) |
                Q(labels__text__icontains=query)
            ).distinct()
        print(queryset)
        return queryset


class NoteEditAPIView(RetrieveUpdateAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteComposeUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        if not self.request.user.is_anonymous:
            serializer.save(author=self.request.user)
        else:
            pass


class NoteDeleteAPIView(DestroyAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteListSerializer


class NoteDetailAPIView(RetrieveAPIView):
    queryset = Note.objects.all()
    serializer_class = NoteDetailSerializer
    # lookup_field = "slug"

notes/views.py
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from notes.forms import NoteForm, LabelForm, NoteArchiveForm
from notes.models import Note, Label
from util import isNotBlank, search, DispatchFunction


class IndexView(generic.ListView):
    template_name = 'notes/index.html'
    context_object_name = 'latest_notes_list'

    def get_queryset(self):
        queryset = Note.objects.all()
        user = self.request.user
        label_param = self.request.GET.get('label')
        user_param = self.request.GET.get('user')
        search_param = self.request.GET.get('q')
        queryset = queryset.filter(Q(public=True) | Q(author__username=user)).filter(archived=False)
        if isNotBlank(label_param):
            queryset = queryset.filter(labels__text=label_param)
        if isNotBlank(user_param):
            queryset = queryset.filter(author__username=user_param)
        if isNotBlank(search_param):
            MODEL_MAP = {Note: ["author__username", "note_title", "note_text", "labels__text"], }
            queryset = search(search_param, queryset, MODEL_MAP)
        return queryset.filter(
            updated__lte=timezone.now(),
        ).order_by('-updated') \
            # .order_by('-pinned')


class DetailView(generic.DetailView):
    model = Note
    template_name = 'notes/detail.html'

    def get_queryset(self):
        return Note.objects.filter(updated__lte=timezone.now())

    def get_object(self, queryset=None):
        object = super(DetailView, self).get_object()
        queryset_main = Note.objects.filter(id=object.id)
        queryset = queryset_main.filter(author__username=self.request.user)
        if queryset.count() > 0:
            return object
        queryset = queryset_main.filter(public=True).filter(archived=False)
        if queryset.count() > 0:
            return object
        else:
            return None


class ComposeView(generic.CreateView):
    model = Note
    form_class = NoteForm
    template_name_suffix = '_compose_form'

    def get_success_url(self):
        return reverse('notes:detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super(ComposeView, self).get_context_data(**kwargs)
        context['form'].fields['labels'].queryset = Label.objects.filter(author=self.request.user)
        return context

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            note = form.save(commit=False)
            note.author = request.user
            note.archived = False
            note.save()
            form.save_m2m()
            return HttpResponseRedirect(
                reverse('notes:detail', kwargs={'pk': note.id}))


class ComposeLabelView(generic.CreateView):
    model = Label
    form_class = LabelForm
    template_name_suffix = '_new_form'
    success_url = '/users/profile'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            label = form.save(commit=False)
            queryset = Label.objects.filter(author__username=request.user)
            if queryset.filter(text=form.cleaned_data['text']).exists():
                messages.warning(request, "Label already exists")
                # raise ValidationError("This label already exists")
            else:
                label.author = request.user
                label.save()
                messages.success(request, "Label successfully saved")
            return HttpResponseRedirect(reverse('users:profile'))


class EditView(generic.UpdateView, DispatchFunction):
    model = Note
    form_class = NoteForm
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        context = super(EditView, self).get_context_data(**kwargs)
        context['form'].fields['labels'].queryset = Label.objects.filter(author=self.request.user)
        return context

    def get_success_url(self):
        return reverse('notes:detail', kwargs={'pk': self.object.id})


class EditLabelView(generic.UpdateView, DispatchFunction):
    model = Label
    form_class = LabelForm
    template_name_suffix = '_update_form'
    success_url = '/users/profile'


class DeleteView(generic.DeleteView, DispatchFunction):
    model = Note
    success_url = '/users/profile'


class DeleteLabelView(generic.DeleteView, DispatchFunction):
    model = Label
    success_url = '/users/profile'


class UnarchiveView(generic.UpdateView, DispatchFunction):
    model = Note
    form_class = NoteArchiveForm
    success_url = '/users/profile'
    template_name_suffix = '_unarchive'

templates/notes/detail.html
{% extends "base.html" %}

{% load label_list_note %}
{% load humanize %}

{% block nav %}
    <a href="{% url 'users:profile' %}">Back to your notes</a>
    <br>
    <a href="{% url 'notes:index' %}">Back to common notes</a>
{% endblock %}

{% block content %}
    {% if note %}
        <h2>{{ note.note_title|title|urlize }}
            {#            {% if note.pinned %}&#128204;{% endif %}#}
        </h2>
        <p class="note-body">{{ note.note_text|linebreaks|urlize }}</p>
        <p>Author: <a href="{% url 'notes:index' %}?user={{ note.author.username }}">{{ note.author.username }}</a></p>
        <p class="small">Created : {{ note.timestamp }}</p>
        <p class="small">Last Updated : {{ note.updated }}</p>
        {% if note.archived %}
            <p>Archived Note</p>
        {% endif %}
        {% label_list_note note.labels.all %}
        {% if user.is_authenticated and user == note.author %}
            <a class="btn btn-default pull-right" href="{% url 'notes:edit' note.id %}">Update</a>
        {% endif %}
    {% else %}
        <p>That note doesn't seem to exist.</p>
    {% endif %}
{% endblock %}

templates/notes/index.html
{% extends "base.html" %}

{% load label_list_note %}
{% load label_list_nav %}
{% load humanize %}

{% block nav %}
    {% label_list_nav request user %}
{% endblock %}

{% block content %}
    <div class="row">
        <form method='GET' action='' class="pull-right" style="margin-bottom: 10px">
            <input type='text' name='q' placeholder='Search notes' value='{{ request.GET.q }}'/>
            <input type='submit' value=&#128270; style="margin-right: 15px;">
        </form>
    </div>
    {% if latest_notes_list %}
        <div class="note-wrapper">
            {% for note in latest_notes_list %}
                <div class="note-item">
                    <div class="note-content">
                        <h3>
                            <a href="{% url 'notes:detail' note.id %}">{{ note.note_title|truncatechars:255|title|urlize }}</a>
                            {#                            <span class="pull-right">{% if note.pinned %}&#128204;{% endif %}</span>#}
                        </h3>
                        <p class="note-body">{{ note.note_text|truncatechars:255|linebreaks|urlize }}</p>
                        {% if user.get_username == note.author.username %}
                            <p>Author:
                                <a href="{% url 'users:profile' %}">{{ note.author.username }}</a>
                                (Own Note)
                            </p>
                        {% else %}
                            <p>Author:
                                <a href="{% url 'notes:index' %}?user={{ note.author.username }}">{{ note.author.username }}</a>
                            </p>

                        {% endif %}
                        <p class="small">Created : {{ note.timestamp|naturalday }}</p>
                        <p class="small">Last Updated : {{ note.updated|naturalday }}</p>
                        {% label_list_note note.labels.all %}
                        {% if note.public %}
                            <p class="note-public">Public Note &#128275;</p>
                        {% else %}
                            <p class="note-public">Private Note &#128274;</p>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No notes are available.</p>
    {% endif %}
{% endblock %}

templates/notes/label_confirm_delete.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete label "{{ object.text }}"?</p>
            <a class="btn btn-primary" href="{% url 'users:profile' %}">Back</a>
            <button class="btn btn-danger" type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

templates/notes/label_list_nav.html
<div class='label-list'>
	Filter:
  {% for label in labels %}
      <a class='labels  {% if curr_label == label.text %}active{% endif %}'
         href="{% url 'notes:index' %}?label={{ label.text }}"
         style="color: {{ label.text_color }};background-color: {{ label.background_color }}">
  	{{ label.text }}
	</a>
  {% endfor %}
  <a class='{% if curr_label == None %}active{% endif %}' href="{% url 'notes:index' %}">All</a>
</div>

templates/notes/label_list_note.html
<div class='label-list'>
  {% for label in labels %}
  <a href="{% url 'notes:index' %}?label={{ label.text }}" style="color: {{label.text_color}};background-color: {{label.background_color}}">
  	{{ label.text }}
	</a>
  {% endfor %}
</div>

templates/notes/label_new_form.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <div class="compose-wrapper row">
            <form class="col-xs-12 form-horizontal" action="" method="post">
                {% csrf_token %}
                {% error_messages form.non_field_errors %}
                <div class="form-group">
                    {% error_messages form.text.errors %}
                    <label class="col-xs-1" for="id_text">Text:</label>
                    <div class="col-xs-5">{{ form.text|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.background_color.errors %}
                    <label class="col-xs-1" for="id_background_color">Body Color:</label>
                    <div class="col-xs-5">{{ form.background_color|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.text_color.errors %}
                    <label class="col-xs-1" for="id_text_color">Text Color:</label>
                    <div class="col-xs-5">{{ form.text_color|add_class:"form-control" }}</div>
                </div>
                <button type="submit" class="btn btn-success col-xs-1 col-xs-offset-2">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/notes/label_update_form.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <div class="compose-wrapper row">
            <form class="col-xs-12 form-horizontal" action="" method="post">
                {% csrf_token %}
                {% error_messages form.non_field_errors %}
                <div class="form-group">
                    {% error_messages form.text.errors %}
                    <label class="col-xs-1" for="id_text">Text:</label>
                    <div class="col-xs-5">{{ form.text|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.background_color.errors %}
                    <label class="col-xs-1" for="id_background_color">Body Color:</label>
                    <div class="col-xs-5">{{ form.background_color|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.text_color.errors %}
                    <label class="col-xs-1" for="id_text_color">Text Color:</label>
                    <div class="col-xs-5">{{ form.text_color|add_class:"form-control" }}</div>
                </div>
                <button type="submit" class="btn btn-success col-xs-1 col-xs-offset-2">Update</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/notes/note_compose_form.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <div class="compose-wrapper row">
            <form class="col-xs-12 form-horizontal" action="" method="post">
                {% csrf_token %}
                {% error_messages form.non_field_errors %}
                <div class="form-group">
                    {% error_messages form.note_title.errors %}
                    <label class="col-xs-1" for="id_note_title">Title:</label>
                    <div class="col-xs-5">{{ form.note_title|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.note_text.errors %}
                    <label class="col-xs-1" for="id_note_text">Body:</label>
                    <div class="col-xs-11">{{ form.note_text|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.labels.errors %}
                    <label class="col-xs-1" for="id_labels">Labels:</label>
                    <div class="col-xs-11">{{ form.labels|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.public.errors %}
                    <label class="col-xs-1" for="id_public">Public:</label>
                    <div class="col-xs-1">{{ form.public| add_class:"form-control" }}</div>
                </div>
                {#                <div class="form-group">#}
                {#                    {% error_messages form.pinned.errors %}#}
                {#                    <label class="col-xs-1" for="id_pinned">Pinned:</label>#}
                {#                    <div class="col-xs-1">{{ form.pinned }}</div>#}
                {#                </div>#}

                <button type="submit" class="btn btn-default pull-right">Publish</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/notes/note_confirm_delete.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
<div>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.note_title }}"?</p>
    <a class="btn btn-primary" href="{% url 'users:profile' %}">Back</a>
    <button class="btn btn-danger" type="submit">Delete</button>
  </form>
</div>
{% endblock %}

templates/notes/note_unarchive.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to unarchive note "{{ object.note_title }}"?</p>
            <a class="btn btn-primary" href="{% url 'users:profile' %}">Back</a>
            <button class="btn btn-warning" type="submit">Unarchive</button>
        </form>
    </div>
{% endblock %}

templates/notes/note_update_form.html
{% extends "base.html" %}

{% load add_class %}
{% load error_messages %}

{% block content %}
    <div>
        <div class="compose-wrapper row">
            <form class="col-xs-12 form-horizontal" action="" method="post">
                {% csrf_token %}
                {% error_messages form.non_field_errors %}
                <div class="form-group">
                    {% error_messages form.note_title.errors %}
                    <label class="col-xs-1" for="id_note_title">Title:</label>
                    <div class="col-xs-5">{{ form.note_title|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.note_text.errors %}
                    <label class="col-xs-1" for="id_note_text">Body:</label>
                    <div class="col-xs-11">{{ form.note_text|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.labels.errors %}
                    <label class="col-xs-1" for="id_labels">Labels:</label>
                    <div class="col-xs-11">{{ form.labels|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.public.errors %}
                    <label class="col-xs-1" for="id_public">Public:</label>
                    <div class="col-xs-1">{{ form.public|add_class:"form-control" }}</div>
                </div>
                <div class="form-group">
                    {% error_messages form.archived.errors %}
                    <label class="col-xs-1" for="id_archived">Archive:</label>
                    <div class="col-xs-1">{{ form.archived|add_class:"form-control" }}</div>
                </div>
                {#                <div class="form-group">#}
                {#                    {% error_messages form.pinned.errors %}#}
                {#                    <label class="col-xs-1" for="id_pinned">Pinned:</label>#}
                {#                    <div class="col-xs-1">{{ form.pinned| add_class:"form-control" }}</div>#}
                {#                </div>#}

                <button type="submit" class="btn btn-default pull-right">Update</button>
            </form>
        </div>
    </div>
{% endblock %}