NotesDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.functional import curry
from django.views.defaults import *
from rest_framework_jwt.views import obtain_jwt_token

handler500 = curry(server_error, template_name='500.html')
handler404 = curry(page_not_found, template_name="404.html")
handler403 = curry(permission_denied, template_name='403.html')


urlpatterns = [
    url(r'^', include('notes.urls', namespace='notes')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/users/', include('users.api.urls', namespace='users_api')),
    url(r'^api/notes/', include('notes.api.urls', namespace='notes_api')),
    url(r'^api/token/auth/', obtain_jwt_token),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/', include('allauth.urls')),

]

notes/urls.py
from django.conf.urls import url

from . import views

app_name = 'notes'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),

    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteView.as_view(), name='delete'),

    url(r'^(?P<pk>[0-9]+)/unarchive/$', views.UnarchiveView.as_view(), name='unarchive'),

    url(r'^compose/$', views.ComposeView.as_view(), name='compose'),

    url(r'^newLabel/$', views.ComposeLabelView.as_view(), name='createLabel'),

    url(r'^(?P<pk>[0-9]+)/editLabel/$', views.EditLabelView.as_view(), name='editLabel'),

    url(r'^(?P<pk>[0-9]+)/deleteLabel/$', views.DeleteLabelView.as_view(), name='deleteLabel'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),

    # ex: /users/signup
    url(r'^signup/', views.SignupView.as_view(), name='signup'),
    # ex: /users/login
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    # ex: /users/logout
    url(r'^logout/', auth_views.logout, name='logout'),
    # ex: /users/profile
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
]

templates/base.html
{% load staticfiles %}
{% load label_list_nav %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Noteworthy{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap3.3.6-min.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
    <link href='{% static 'googleOpenSans.css' %}' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static 'notes/css/style.css' %}" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <div class='page'>
    <div class='container header'>
      {% include "header.html" %}
      {% block nav %}{% endblock %}
    </div>
    <div class='container content'>
      {% block content %}{% endblock %}
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

templates/header.html
<h1><a href="{% url 'notes:index' %}">Django Notes</a></h1>
<br>
<div class="registration-controls">
	{% if user.is_authenticated %}
		<span>{{user.username}}</span> | <a href="{% url 'users:profile' %}">Profile</a> | <a href="{% url 'users:logout' %}">Logout</a>
	{% else %}
		<a href="{% url 'users:login' %}">Login</a> | <a href="{% url 'users:signup' %}">Sign up</a>
	{% endif %}
</div>