NotesDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.functional import curry
from django.views.defaults import *
from rest_framework_jwt.views import obtain_jwt_token

handler500 = curry(server_error, template_name='500.html')
handler404 = curry(page_not_found, template_name="404.html")
handler403 = curry(permission_denied, template_name='403.html')


urlpatterns = [
    url(r'^', include('notes.urls', namespace='notes')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
    url(r'^api/users/', include('users.api.urls', namespace='users_api')),
    url(r'^api/notes/', include('notes.api.urls', namespace='notes_api')),
    url(r'^api/token/auth/', obtain_jwt_token),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/', include('allauth.urls')),

]

notes/urls.py
from django.conf.urls import url

from . import views

app_name = 'notes'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),

    url(r'^(?P<pk>[0-9]+)/delete/$', views.DeleteView.as_view(), name='delete'),

    url(r'^(?P<pk>[0-9]+)/unarchive/$', views.UnarchiveView.as_view(), name='unarchive'),

    url(r'^compose/$', views.ComposeView.as_view(), name='compose'),

    url(r'^newLabel/$', views.ComposeLabelView.as_view(), name='createLabel'),

    url(r'^(?P<pk>[0-9]+)/editLabel/$', views.EditLabelView.as_view(), name='editLabel'),

    url(r'^(?P<pk>[0-9]+)/deleteLabel/$', views.DeleteLabelView.as_view(), name='deleteLabel'),

]

users/api/urls.py
from django.conf.urls import url

from users.api.views import UserCreateAPIView, UserListAPIView, UserLoginAPIView

urlpatterns = [
    url(r'^signup/$', UserCreateAPIView.as_view(), name='signup'),
    url(r'^$', UserListAPIView.as_view(), name='list'),
    url(r'^login/$', UserLoginAPIView.as_view(), name='login'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),

    # ex: /users/signup
    url(r'^signup/', views.SignupView.as_view(), name='signup'),
    # ex: /users/login
    url(r'^login/', auth_views.login, name='login', kwargs={'redirect_authenticated_user': True}),
    # ex: /users/logout
    url(r'^logout/', auth_views.logout, name='logout'),
    # ex: /users/profile
    url(r'^profile/', views.ProfileView.as_view(), name='profile'),
]

users/api/views.py
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from django.contrib.auth import get_user_model
from rest_auth.registration.views import SocialLoginView
from rest_framework.generics import ListAPIView, CreateAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from rest_framework.views import APIView

from .serializers import UserCreateSerializer, UserListSerializer, UserLoginSerializer

User = get_user_model()


class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter



class UserCreateAPIView(CreateAPIView):
    serializer_class = UserCreateSerializer
    queryset = User.objects.all()


class UserListAPIView(ListAPIView):
    serializer_class = UserListSerializer
    queryset = User.objects.all()


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)

        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors)

users/views.py
# import requests


from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from notes.models import Note, Label
from notes.views import search
from util import isNotBlank


def index(request):
    return render(request, 'users/index.html', {})


class SignupView(generic.View):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'

    def get(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('users:profile'))
        else:
            return render(
                request,
                self.template_name,
                {'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # recaptcha_response = request.POST.get('g-recaptcha-response')
            # data = {
            #     'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            #     'response': recaptcha_response
            # }
            # r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            # result = r.json()
            # print(result)
            # ''' End reCAPTCHA validation '''

            # if result['success']:
            new_user = authenticate(username=username, password=password, )
            user.save()
            login(request, new_user)
            return HttpResponseRedirect(reverse('users:profile'))
        return render(request, self.template_name, {'form': form})


class ProfileView(generic.DetailView):
    model = User
    template_name = 'users/profile.html'

    def get(self, request, **kwargs):
        if request.user.is_authenticated():
            search_param = self.request.GET.get('q')
            notes_non_archived = Note.objects.filter(author=request.user).filter(archived=False).order_by('-updated')
            notes_archived = Note.objects.filter(author=request.user).filter(archived=True).order_by('-updated')
            if isNotBlank(search_param):
                MODEL_MAP = {Note: ["note_title", "note_text", "labels__text"], }
                notes_non_archived = search(search_param, notes_non_archived, MODEL_MAP)
            labels = Label.objects.filter(author__username=request.user)
            return render(request, self.template_name,
                          {'notes': notes_non_archived, 'labels': labels, 'notes_archived': notes_archived})
        return HttpResponseRedirect(reverse('notes:index'))

templates/users/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 text-center">
            {% if user.is_authenticated %}
                <h2>Welcome, {{ user.username }}!</h2>
                <a class="btn btn-default" href="{% url 'notes:index' %}">NOTE FEED</a>
                <a class="btn btn-default" href="{% url 'users:profile' %}">YOUR PROFILE</a>
            {% else %}
                <h2>Welcome!</h2>
                <a class="btn btn-default" style="margin-right: 10px" href="{% url 'users:signup' %}">SIGN UP</a>
                <a class="btn btn-default" href="{% url 'users:login' %}">LOGIN</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends "base.html" %}

{% load label_list_note %}
{% load label_list_nav %}
{% load add_class %}
{% load error_messages %}
{% load humanize %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <div class="profile-content">

    <a class="btn btn-success pull-right" href="{% url 'notes:compose' %}">COMPOSE NOTE</a>
    <a class="btn btn-success pull-right" style="margin-right: 10px" href="{% url 'notes:createLabel' %}">CREATE
        LABEL</a>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Your
            notes</a></li>
        <li role="presentation"><a href="#archived" aria-controls="archived" role="tab" data-toggle="tab">Your
            archived notes</a></li>

        <li role="presentation"><a href="#labels" aria-controls="labels" role="tab" data-toggle="tab">Your
            labels</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="home">
            <div class="row">
                <form method='GET' action='' class="pull-right" style="margin-bottom: 10px">
                    <input type='text' name='q' placeholder='Search from your notes' value='{{ request.GET.q }}'/>
                    <input type='submit' value=&#128270; style="margin-right: 15px;">
                </form>
            </div>
            <div class="note-wrapper">
                {% if notes %}
                    {% for note in notes %}
                        <div class="note-item">
                            <div class="note-controls">
                                <a class="btn btn-success" href="{% url 'notes:detail' note.id %}">View</a>
                                <a class="btn btn-primary" href="{% url 'notes:edit' note.id %}">Edit</a>
                                <a class="btn btn-danger" href="{% url 'notes:delete' note.id %}">Delete</a>
                            </div>
                            <div class="note-content">
                                <h3>
                                    <a href="{% url 'notes:detail' note.id %}">{{ note.note_title|truncatechars:255|title|urlize }}</a>
                                    {#                                    <span class="pull-right">{% if note.pinned %}&#128204;{% endif %}</span>#}

                                </h3>
                                <p class="note-body">{{ note.note_text|truncatechars:255|linebreaks|urlize }}</p>
                                <p class="small">Created : {{ note.timestamp|naturalday }}</p>
                                <p class="small">Last Updated : {{ note.updated|naturalday }}</p>
                                {% label_list_note note.labels.all %}
                                {% if note.public %}
                                    <p class="note-public">Public Note &#128275;</p>
                                {% else %}
                                    <p class="note-public">Private Note &#128274;</p>
                                {% endif %}

                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No notes available!</p>
                {% endif %}
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade in " id="archived">
            <div class="note-wrapper">
                {% if notes_archived %}
                    {% for note in notes_archived %}
                        <div class="note-item">
                            <div class="note-controls">
                                <a class="btn btn-success" href="{% url 'notes:detail' note.id %}">View</a>
                                <a class="btn btn-primary" href="{% url 'notes:edit' note.id %}">Edit</a>
                                <a class="btn btn-danger" href="{% url 'notes:delete' note.id %}">Delete</a>
                                <a class="btn btn-warning" href="{% url 'notes:unarchive' note.id %}">Unarchive</a>
                            </div>
                            <div class="note-content">
                                <h3>
                                    <a href="{% url 'notes:detail' note.id %}">{{ note.note_title|truncatechars:255|title|urlize }}</a>
                                    {#                                    <span class="pull-right">{% if note.pinned %}&#128204;{% endif %}</span>#}

                                </h3>
                                <p class="note-body">{{ note.note_text|truncatechars:255|linebreaks|urlize }}</p>
                                <p class="small">Created : {{ note.timestamp|naturalday }}</p>
                                <p class="small">Last Updated : {{ note.updated|naturalday }}</p>
                                {% label_list_note note.labels.all %}
                                {% if note.public %}
                                    <p class="note-public">Public Note &#128275;</p>
                                {% else %}
                                    <p class="note-public">Private Note &#128274;</p>
                                {% endif %}

                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>You don't have any notes archived yet!</p>
                {% endif %}
            </div>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="labels">
            {% if labels %}
                <div class="row">
                {% for label in labels %}
                    <div class="row" style="margin-bottom: 10px">

                        <div class="col-xs-2 col-xs-offset-1 text-center my_label_class btn btn-default"
                             style="color: {{ label.text_color }}; background-color: {{ label.background_color }}"> {{ label.text }}</div>
                        <div class="col-xs-2 col-xs-offset-1 text-center "><a
                                href="{% url 'notes:editLabel' label.id %}" style="color: #325d88;">Edit</a></div>
                        <div class="col-xs-2 col-xs-offset-1 text-center "><a
                                href="{% url 'notes:deleteLabel' label.id %}" style="color: #d9534f">Delete</a></div>
                    </div>

                {% endfor %}
            {% else %}
                <p>No Notes!</p>
            {% endif %}

            </div>
        </div>

    </div>
{% endblock %}